dist: xenial
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: uq+v+whRSJWmIvlbY+RvUsDWMCuLE5zH1IEoLVhy8m7InL/YkC+iBFl+vmAsi1gq0twIBCiqE7jVI7221WvWUeN30vz815qDlR8FMqP9IKQExAR5EHkK2KCNbd+2JqPvtNemIMNi0mQLC6soOvO9KoZnzHsEMebnBI3CpJ39jIFvkocVN/ogL11utmF8NHdMGXsivCsR7Rpsl2L+OaGQ3/35h3vzkepcmqUEy0J5SAvlS+ZHDwKMe55CqmXNvysyGYL8wt2V7PwhptXd2CKJIdQGG2kFQEsm8AuL0F10AgGOBS2p6jhAiLLVumc8DoUT3fthVTFx2eILUKYeFJNKq5FAev4UMlTTlHkJRdUzhaju+5YWZao/2tWGicjMzb1YW9piI1xxeO3yNU9QnoX1iAh06xWGW7wTscvDbTCFQIfj1i/b9nvTDmWHpltQHOwoyAhsUzYg74xi4wMfTE55CvfR/knss9wciLHQiB3d9vMw3ARZn0mji2WUv/gJNCZ5/YdlrLU75FyhCWpIIuLdhRVzICChDwggFmY76wGFJ5O//qhV5VNmD39SXVqvduwVLxCqEtWseH02bUKKGNnxvYL8RmwJdjUB3ho6ZZP2TYsVyvdBBIxxoSbrwvuI8nf+mw+uK2HkkRn5/aYu2/rJybk4sCnjjeRt9shQ7uhyeF4=
